name: Build LEDE tl-wdr7500-v3

on:
  push:
    branches: [master]

env:
  TARGET_DEVICE: tl-wdr7500-v3
  TOTAL_KEEP_NUMBER: 20

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo swapoff -a
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler coreutils
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean

          WORKING_DIR="$GITHUB_WORKSPACE"
          echo "WORKING_DIR=${WORKING_DIR}" >>$GITHUB_ENV
          cd "${WORKING_DIR}"
          LEDE_VERSION="$(cat "${WORKING_DIR}/version")"
          echo "LEDE_VERSION=${LEDE_VERSION}" >>$GITHUB_ENV
          LEDE_OUTPUT_NAME="lede-${LEDE_VERSION}-${TARGET_DEVICE}"
          echo "LEDE_OUTPUT_NAME=${LEDE_OUTPUT_NAME}" >>$GITHUB_ENV
          echo "FIRMWARE=${WORKING_DIR}/out" >> $GITHUB_ENV

      - name: Load custom configuration
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          ./clean_all.sh
          cp -f "conf/.config.$TARGET_DEVICE" .config        
          make defconfig V=s

      - name: Download package
        id: package
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          make download -j8 || make download -j1 V=s
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile firmware
        id: compile
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          echo -e "$(($(nproc) + 1)) thread compile"
          make -j$(($(nproc) + 1)) || make -j1 V=s
          rm -rf ${FIRMWARE}
          mkdir -p ${FIRMWARE}
          cp -u -f bin/targets/*/*/${LEDE_OUTPUT_NAME}-*-sysupgrade.bin ${FIRMWARE}/
          cd ${FIRMWARE}/
          for f in *.bin; do mv "$f" "$(echo "$f" | sed -e 's/-squashfs//g' -e 's/-sysupgrade//g')"; done
          echo "::set-output name=status::success"

      - name: Upload firmware directory
        uses: actions/upload-artifact@master
        if: steps.compile.outputs.status == 'success'        
        with:
          name: ${{ env.LEDE_OUTPUT_NAME }}
          path: ${{ env.FIRMWARE }}

      - name: Upload firmware to cowtransfer
        id: cowtransfer
        if: steps.compile.outputs.status == 'success'
        working-directory: ${{ env.WORKING_DIR }}
        continue-on-error: true
        run: |
          curl -fsSL git.io/file-transfer | sh
          ./transfer cow --block 2621440 -s -p 64 --no-progress ${FIRMWARE} 2>&1 | tee cowtransfer.log
          echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
          echo "::set-output name=url::$(cat cowtransfer.log | grep https | cut -f3 -d" ")"

      - name: Upload firmware to CatBox
        id: catbox
        if: steps.compile.outputs.status == 'success'
        working-directory: ${{ env.WORKING_DIR }}
        continue-on-error: true
        run: |
          curl -fsSL git.io/file-transfer | sh
          ./transfer cat --no-progress ${FIRMWARE} 2>&1 | tee catbox.log
          echo "::warning file=catbox.com::$(cat catbox.log | grep https)"
          echo "::set-output name=url::$(cat catbox.log | grep https | cut -f3 -d" ")"

      - name: Upload firmware to anonfiles
        id: anonfiles
        if: steps.compile.outputs.status == 'success'
        working-directory: ${{ env.WORKING_DIR }}
        continue-on-error: true
        run: |
          upfile="${FIRMWARE}/${LEDE_OUTPUT_NAME}.bin"
          for i in $(seq 1 5); do downurl="$(curl -F file=@${upfile}  https://api.anonfiles.com/upload 2>/dev/null | tee | tr '\"' '\n' | grep "^https" | head -n 1)"; [ -n ${downurl} ] && break; done
          echo "::warning file=anonfiles.com::Download Link: ${downurl}"
          echo "::set-output name=url::${downurl}"

      - name: Upload firmware to anonymousfiles
        id: anonymousfiles
        if: steps.compile.outputs.status == 'success'
        working-directory: ${{ env.WORKING_DIR }}
        continue-on-error: true
        run: |
          upfile="${FIRMWARE}/${LEDE_OUTPUT_NAME}.bin"
          for i in $(seq 1 5); do downurl="$(curl -F file=@${upfile} -F expires=6m https://api.anonymousfiles.io/ 2>/dev/null | tee | tr '\"' '\n' | grep "^https" | head -n 1)"; [ -n ${downurl} ] && break; done
          echo "::warning file=anonymousfiles.io::Download Link: ${downurl}"
          echo "::set-output name=url::${downurl}"

      - name: Generate release tag
        id: tag
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          echo "::set-output name=release_tag::${LEDE_OUTPUT_NAME}"
          touch "$WORKING_DIR/release.txt"
          echo "ðŸ”— [å¥¶ç‰›å¿«ä¼ ä¸‹è½½](${{ steps.cowtransfer.outputs.url }})" >> "$WORKING_DIR/release.txt"
          echo "ðŸ”— [CatBoxä¸‹è½½](${{ steps.catbox.outputs.url }})" >> "$WORKING_DIR/release.txt"
          echo "ðŸ”— [anonfilesä¸‹è½½](${{ steps.anonfiles.outputs.url }})" >> "$WORKING_DIR/release.txt"
          echo "ðŸ”— [AnonymousFilesä¸‹è½½](${{ steps.anonymousfiles.outputs.url }})" >> "$WORKING_DIR/release.txt"
          cd "${FIRMWARE}"
          echo "" >> "$WORKING_DIR/release.txt"
          echo "æ–‡ä»¶MD5æ ¡éªŒï¼š" >> "$WORKING_DIR/release.txt"
          md5sum *.bin | awk '{print $2,$1}' >> "$WORKING_DIR/release.txt"
          echo "" >> "$WORKING_DIR/release.txt"
          echo "ä»¥ä¸Šæ‰€æœ‰é“¾æŽ¥çš„æ–‡ä»¶å‡ç›¸åŒï¼Œä¸åŒç½‘ç›˜è¿‡æœŸæ—¶é—´ä¸åŒï¼Œä»…éœ€ä¸‹è½½å…¶ä¸­ä¸€ä¸ªé“¾æŽ¥å³å¯ã€‚è‹¥ä»¥ä¸Šé“¾æŽ¥å‡è¿‡æœŸå¤±æ•ˆæˆ–æ— æ³•æ‰“å¼€ï¼Œè¯·åœ¨ä»¥ä¸‹Assetsä¸­ä¸‹è½½æ–‡ä»¶ã€‚ä¸‹è½½åŽè¯·æ ¸å¯¹æ–‡ä»¶MD5æ ¡éªŒã€‚" >> "$WORKING_DIR/release.txt"
          echo "::set-output name=status::success"

      - name: Upload firmware to release
        uses: HiGarfield/action-gh-release@v1
        if: steps.tag.outputs.status == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body_path: ${{ env.WORKING_DIR }}/release.txt
          files: ${{ env.FIRMWARE }}/*

      - name: Remove old releases
        uses: HiGarfield/delete-older-releases@v0.1.0
        continue-on-error: true
        with:
          keep_latest: ${{ env.TOTAL_KEEP_NUMBER }}
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
